apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: odoo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-postgres
  namespace: odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo-postgres
  template:
    metadata:
      labels:
        app: odoo-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_USER
              value: "odoo"
            - name: POSTGRES_PASSWORD
              value: "odoo" # TODO: sensitive values should be stored as Kubernetes secrets instead
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: pgdata # required to avoid error:
              # initdb: error: directory "/var/lib/postgresql/data" exists but is not empty
              # It contains a lost+found directory, perhaps due to it being a mount point.
              # Using a mount point directly as the data directory is not recommended.
              # Create a subdirectory under the mount point.
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-postgres
  namespace: odoo
spec:
  selector:
    app: odoo-postgres
  ports:
    - port: 5432
      targetPort: 5432
